"""Made the show id nullable for artist incase they have no shows scheduled

Revision ID: ee3cc39d8d92
Revises: ea320e837fd2
Create Date: 2022-07-22 16:26:02.634385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3cc39d8d92'
down_revision = 'ea320e837fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
